import pandas as pd
from src.automation.email_sender import EmailSender

def main():
    print("🚀 Module 2 Initialization: Bulk Email Automation Campaign...")
    
    try:
        # Load the 'Email Ready' sheet generated by Module 1
        df = pd.read_excel("data/ceo_data.xlsx", sheet_name="Email Ready")
    except Exception as e:
        print(f"❌ Failed to load ceo_data.xlsx: {e}")
        return

    if df.empty:
        print("⚠️ No valid emails found in 'Email Ready' sheet.")
        return

    # Prepare recipient data list for the EmailSender
    recipient_data = []
    for _, row in df.iterrows():
        # Ensure we have the required fields
        email = row.get("Email Address")
        full_name = row.get("Full Name", "Leader")
        company = row.get("Company Name", "your company")
        industry = row.get("Industry", "your industry")
        
        if pd.isna(email) or not email:
            continue
            
        first_name = str(full_name).split()[0] if full_name else "there"
        
        recipient_data.append({
            "email": str(email),
            "first_name": first_name,
            "company": str(company),
            "industry": str(industry)
        })

    print(f"✅ Loaded {len(recipient_data)} verified contacts from 'Email Ready' sheet.")
    
    # Initialize Sender and Dispatch
    sender = EmailSender()
    success = sender.send_bulk_email(recipient_data)
    
    if success:
        print("\n✅ Module 2 Complete: Bulk Outreach campaign successfully executed.")
    else:
        print("\n❌ Campaign failed to execute properly.")

if __name__ == "__main__":
    main()
